name: "CICD Pipeline for Feature Branches"

# Trigger WF only for Features
on:
  pull_request:
    branches: [ feature/* ]

# Workflow Variables
#env:
#  ENVIRONMENT: feature

# Jobs
jobs:
  build-and-install:
    uses: ./.github/workflows/build.yml
    with:
      environment: feature

  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: feature