name: "CICD Pipeline for Feature Branches"

# Trigger WF only for Features
on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - feature/*

# Workflow Variables
#env:
#  ENVIRONMENT: feature

# Jobs
jobs:
  build-and-install:
    uses: ./.github/workflows/build.yml
    with:
      environment: feature

  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: feature

  ending:
    runs-on: ubuntu-latest
    steps:
      - name: End of Pipeline
        run: echo "End of Pipeline ${{ github.branch }}"