name: "CICD Pipeline for Main Branch"

# Trigger WF only for Main
on:
  push:
    branches: [ main ]

# Workflow Variables
env:
  ENVIRONMENT: main

# Jobs
jobs:
  build-and-install:
    uses: ./.github/workflows/_build.yaml
    with:
      environment: ${{ env.ENVIRONMENT }}

  deploy:
    uses: ./.github/workflows/reusables/_deploy.yaml
    with:
      environment: ${{ env.ENVIRONMENT }}